// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcMonitorWebApi.Data;

#nullable disable

namespace PcMonitorWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastBootTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemArchitecture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkgroupOrDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProcessorId");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.DiskDrive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityGB")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("DiskDrive");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.GraphicsCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VRAMGB")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("GraphicsCard");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.MemoryModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityGB")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("MemoryModule");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.NetworkInterface", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("IPAddresses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MACAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SubnetMasks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("NetworkInterface");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.Processor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Threads")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Processor");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.Computer", b =>
                {
                    b.HasOne("PcMonitorWebApi.Data.Models.Group", "Group")
                        .WithMany("Computers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PcMonitorWebApi.Data.Models.Processor", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Processor");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.DiskDrive", b =>
                {
                    b.HasOne("PcMonitorWebApi.Data.Models.Computer", null)
                        .WithMany("DiskDrives")
                        .HasForeignKey("ComputerId");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.GraphicsCard", b =>
                {
                    b.HasOne("PcMonitorWebApi.Data.Models.Computer", null)
                        .WithMany("GraphicsCards")
                        .HasForeignKey("ComputerId");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.MemoryModule", b =>
                {
                    b.HasOne("PcMonitorWebApi.Data.Models.Computer", null)
                        .WithMany("MemoryModules")
                        .HasForeignKey("ComputerId");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.NetworkInterface", b =>
                {
                    b.HasOne("PcMonitorWebApi.Data.Models.Computer", null)
                        .WithMany("NetworkInterfaces")
                        .HasForeignKey("ComputerId");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.Computer", b =>
                {
                    b.Navigation("DiskDrives");

                    b.Navigation("GraphicsCards");

                    b.Navigation("MemoryModules");

                    b.Navigation("NetworkInterfaces");
                });

            modelBuilder.Entity("PcMonitorWebApi.Data.Models.Group", b =>
                {
                    b.Navigation("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
